### ISSUE TITLE
Mouse

### ISSUE THREAD

**Issue by alr1976** [rdp/on-screen-capture-recorder-to-video-windows-free#11]
How Can i disable mouse pointer when use screen recording?
Can i disable walppaper?

**Comment by rdp** [comment]
there is a setting for the mouse I think:https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/master/configuration_setup_utility/setup_screen_tracker_params.rb#L9
disable wallpaper nothing yet...you could file an issue for it here: https://github.com/rdp/screen-capture-recorder-to-video-windows-free and if you provide funding, I might do it! :)
