### ISSUE TITLE
how to tell the program to use a specific JRE / JDK ?

### ISSUE THREAD

**Issue by dif1754** [rdp/on-screen-capture-recorder-to-video-windows-free#7]
Hi

I have 2 java jdk and 2 java jre on my laption (vers. 1.6 and 1.8) for developing reasons...
1.6 was installed first, later I installed the 1.8 version.

How can I tell the program to use a specific JRE without watching the Windows registry?

Now, when I try to run the program I get the following error:

C:\Program Files (x86)\Screen Capturer Recorder\configuration_setup_utility>generic_run_rb.bat
you need to install java JRE first please install it from java.com then run again
Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.
Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.

Environment vars point to JRE 1.6 (I have to), but the registry point to 1.8 (latest version installed).

How to solve the problem?

Thanks

**Comment by rdp** [comment]
yikes I had no idea it required 1.6 what?
does java -version work?
I would guess it doesn't, if it doesn't...hmm...you may be able to modify
your system path so that it points to the right one first [maybe even in
that very batch file...]
GL!

https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/master/configuration_setup_utility/generic_run_rb.bat

**Comment by dif1754** [comment]
Unfortunately it does not work... I set a new PATH inside the .bat , specific for the 1.6 java version (I put a rem in front of the previous "set path" statements because otherwise I would get and error....

please, look the screenshot:
https://www.dropbox.com/s/cidtva2252zrviq/Screenshot%20-%2006_11_2014%20%2C%2017_13_13.png?dl=0

After the icon appears, the program is not loaded... it seems stucked.

any idea?

PS
besides the java inside the specific folders of the specific java versions, there are jre apps inside the %WINDIR%\syswow64 and references inside the Windows registry.... If I try to remove those files inside the syswow64 dir, I would get error messages about the java version from the registry...

**Comment by dif1754** [comment]
SOLVED:

I forced the PATH and JAVA_HOME env vars to the 1.8 java versions, just  inside the generic_run_rb.bat

set JAVA_HOME=C:\jdk1.8.0_25
set PATH=c:\jre1.8.0_25\bin\

and all works.

PS
previously I did the same, but I had the bad idea to run the generic_run_rb.bat from the dos consolle (without parameters), I did not run the "Screen Capturer Recorder" menu items inside the Start menu :P

**Comment by rdp** [comment]
nice thanks for the writeup
